routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::group(['middleware'=>'auth'], function(){

    // TYPE DE FORMATION
    Route::resource('typeFormations','TypeFormationController');

    // TYPE FONCTION
    Route::resource('typeFonctions','TypeFonctionController');


    // DEPARTEMENT
    Route::resource('departements','DepartementController');
    // FONCTION
    Route::resource('fonctions','FonctionController');
    Route::get('fonctions/{slug}','FonctionController@show')->name('fonctions.show');
});

// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');



Route::resource('employes','EmployeController');
// Route::get('employes/{slug}','EmployeController@show')->name('employes.show');
// Route::get('employes/{slug}','EmployeController@edit')->name('employes.edit');
Route::get('demission-employes/{id}','EmployeController@Demission')->name('demission');

// route training
Route::resource('formations','FormationController');

// gestion des sanction
Route::resource('sanctions','SanctionController');
Route::post('sanctions/{id}','SanctionController@decision')->name('decision.index');






// ABSENCES
Route::resource('absences','AbsenceController');

Route::post('absences/{id}','AbsenceController@justify')->name('justify.index');
// Route::post('absences-arpport/{id}','AbsenceController@rapport')->name('rapport.index');
Route::get('/absences-demission-accepte/{id}', 'AbsenceController@Etat_accepte_demission')->name('accepte_demission');
Route::get('/absences-demission-refuse/{id}','AbsenceController@Etat_refus_demission')->name('refuse_demission');


// CONGES
Route::resource('conges','CongeController');
Route::delete('conges/{slug}', 'CongeController@destroy')->name('conges.destroy');

// Route::get('/liste-conges-en-cours', 'CongeController@listeCongesEnAttente')->name('CongeEnAttente');

Route::get('/conge-valide/{id}', 'CongeController@Accepte')->name('congeValide');
Route::get('/rejetter/{id}','CongeController@Refuse')->name('congeRefuse');
Route::post('/conges/{id}','CongeController@Autorisation')->name('autorisations');



Route::resource('groupes', 'GroupeController');


Route::resource('typeSanctions', 'Type_sanctionController');


Route::resource('dossierEmployes', 'Dossier_employeController');
Route::post('dossier', 'EmployeController@Dossier')->name('dossier.store');


Route::resource('typeFonctions', 'Type_fonctionController');


Route::resource('typeFormations', 'Type_formationController');
Route::get('send', 'HomeController@sendNotification');


Route::resource('villes', 'VilleController');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Type_formation.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class Type_formation
 * @package App\Models
 * @version August 5, 2021, 4:29 pm UTC
 *
 * @property string $libelle
 */
class Type_formation extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'type_formations';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'libelle'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'libelle' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/Type_formationController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateType_formationRequest;
use App\Http\Requests\UpdateType_formationRequest;
use App\Repositories\Type_formationRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class Type_formationController extends AppBaseController
{
    /** @var  Type_formationRepository */
    private $typeFormationRepository;

    public function __construct(Type_formationRepository $typeFormationRepo)
    {
        $this->typeFormationRepository = $typeFormationRepo;
    }

    /**
     * Display a listing of the Type_formation.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $typeFormations = $this->typeFormationRepository->all();

        return view('type_formations.index')
            ->with('typeFormations', $typeFormations);
    }

    /**
     * Show the form for creating a new Type_formation.
     *
     * @return Response
     */
    public function create()
    {
        return view('type_formations.create');
    }

    /**
     * Store a newly created Type_formation in storage.
     *
     * @param CreateType_formationRequest $request
     *
     * @return Response
     */
    public function store(CreateType_formationRequest $request)
    {
        $input = $request->all();

        $typeFormation = $this->typeFormationRepository->create($input);

        Flash::success('Type Formation saved successfully.');

        return redirect(route('typeFormations.index'));
    }

    /**
     * Display the specified Type_formation.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $typeFormation = $this->typeFormationRepository->find($id);

        if (empty($typeFormation)) {
            Flash::error('Type Formation not found');

            return redirect(route('typeFormations.index'));
        }

        return view('type_formations.show')->with('typeFormation', $typeFormation);
    }

    /**
     * Show the form for editing the specified Type_formation.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $typeFormation = $this->typeFormationRepository->find($id);

        if (empty($typeFormation)) {
            Flash::error('Type Formation not found');

            return redirect(route('typeFormations.index'));
        }

        return view('type_formations.edit')->with('typeFormation', $typeFormation);
    }

    /**
     * Update the specified Type_formation in storage.
     *
     * @param int $id
     * @param UpdateType_formationRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateType_formationRequest $request)
    {
        $typeFormation = $this->typeFormationRepository->find($id);

        if (empty($typeFormation)) {
            Flash::error('Type Formation not found');

            return redirect(route('typeFormations.index'));
        }

        $typeFormation = $this->typeFormationRepository->update($request->all(), $id);

        Flash::success('Type Formation updated successfully.');

        return redirect(route('typeFormations.index'));
    }

    /**
     * Remove the specified Type_formation from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $typeFormation = $this->typeFormationRepository->find($id);

        if (empty($typeFormation)) {
            Flash::error('Type Formation not found');

            return redirect(route('typeFormations.index'));
        }

        $this->typeFormationRepository->delete($id);

        Flash::success('Type Formation deleted successfully.');

        return redirect(route('typeFormations.index'));
    }
}

resources/views/front/type_formations/create.blade.php
@extends('layouts.main')
@section('content')


  <!-- Navbar -->
    @include('layouts.header')
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->

  @include('layouts.sidebars')
  <!-- Content Wrapper. Contains page content -->
 <!-- Content Wrapper. Contains page content -->
 <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="mb-2 row">
          <div class="col-sm-6">
            {{-- <h1 class="m-0">Tableau de bord</h1> --}}
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Accueil</a></li>
              <li class="breadcrumb-item active">Créer un type de formation</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
        <div class="row">
            <div class="col-12">


            <div class="card card-info">
                <div class="card-header">
                <h3 class="card-title">Créer un type de formation</h3>
                <span class="breadcrumb float-sm-right"><a href="{{route('typeFormations.index')}}">Retour</a></span>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                     <!-- form start -->
              <form method="POST" enctype="multipart/form-data" action="{{route('typeFormations.store')}}">
                @csrf
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Libelle</label>
                                <input type="text"name="libelle" class="form-control">
                              </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Description</label>
                                <input type="text" name="description" class="form-control">
                              </div>
                        </div>
                       
                    </div>

                <div class="card-footer">
                  <button type="submit" class="btn btn-success">Enregistrer</button>
                </div>
              </form>

                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
  </section>
  <!-- /.content -->
        <!-- /.row (main row) -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  {{-- footer --}}
  @include('layouts.footer')
  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

@endsection

resources/views/front/type_formations/edit.blade.php
@extends('layouts.main')
@section('content')


  <!-- Navbar -->
    @include('layouts.header')
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->

  @include('layouts.sidebars')
  <!-- Content Wrapper. Contains page content -->
 <!-- Content Wrapper. Contains page content -->
 <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="mb-2 row">
          <div class="col-sm-6">
            {{-- <h1 class="m-0">Tableau de bord</h1> --}}
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Accueil</a></li>
              <li class="breadcrumb-item active">Créer un type de formation</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
        <div class="row">
            <div class="col-12">


            <div class="card card-info">
                <div class="card-header">
                <h3 class="card-title">Créer un type de formation</h3>
                <span class="breadcrumb float-sm-right"><a href="{{route('typeFormations.index')}}">Retour</a></span>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                     <!-- form start -->
              <form method="POST" enctype="multipart/form-data" action="{{route('typeFormations.store')}}">
                @csrf
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Libelle</label>
                                <input type="text"name="libelle" value="{{$type_formation->libelle}}" class="form-control">
                              </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Description</label>
                                <input type="text" name="description"value="{{$type_formation->description}}" class="form-control">
                              </div>
                        </div>
                       
                    </div>

                <div class="card-footer">
                  <button type="submit" class="btn btn-success">Enregistrer</button>
                </div>
              </form>

                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
  </section>
  <!-- /.content -->
        <!-- /.row (main row) -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  {{-- footer --}}
  @include('layouts.footer')
  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

@endsection

resources/views/front/type_formations/index.blade.php
@extends('layouts.main')
@section('content')


  <!-- Navbar -->
    @include('layouts.header')
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->

  @include('layouts.sidebars')
  <!-- Content Wrapper. Contains page content -->
 <!-- Content Wrapper. Contains page content -->
 <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="mb-2 row">
          <div class="col-sm-6">
            {{-- <h1 class="m-0">Tableau de bord</h1> --}}
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Accueil</a></li>
              <li class="breadcrumb-item active">Type formation</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    
 <!-- Main content -->
 <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">


          <div class="card card-info">
            <div class="card-header">
              <h3 class="card-title">Liste type formation</h3>
              <span class="breadcrumb float-sm-right"><a href="{{route('typeFormations.create')}}">Ajouter</a></span>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>Libelle</th>
                    <th>Description</th>
                    <th class="min-width: 100px">Actions</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($types_formations as $type_formation)
                        <tr>
                            <td>{{$type_formation->libelle}}</td>
                            <td>{{$type_formation->description}}</td>
                            <td>
                                <div class="d-flex align-items-center list-user-action">
                                    <a class="mr-1 btn btn-sm bg-primary" data-toggle="tooltip" data-placement="top" title=""
                                        data-original-title="Voir profil" href="{{route('typeFormations.show',$type_formation->id)}}">
                                        <i class="far fa-eye"></i>
                                    </a>
                                    <a class="mr-1 btn btn-sm bg-primary" data-toggle="tooltip" data-placement="top" title=""
                                        data-original-title="Edit" href="{{route('typeFormations.edit',$type_formation->id)}}"><i class="far fa-edit"></i></a>

                                    <form class="btn btn-sm bg-danger" data-toggle="tooltip" data-placement="top" title=""
                                    data-original-title="Delete" method="POST" action="{{route('typeFormations.destroy',$type_formation->id)}}">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class=""><i class="far fa-trash-alt"></i></button>

                                    </form>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </tfoot>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
  </section>
  <!-- /.content -->
        <!-- /.row (main row) -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  {{-- footer --}}
  @include('layouts.footer')
  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

@endsection