routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::group(['middleware'=>'auth'], function(){

    // TYPE DE FORMATION
    Route::resource('typeFormations','TypeFormationController');

    // TYPE FONCTION
    Route::resource('typeFonctions','TypeFonctionController');


    // DEPARTEMENT
    Route::resource('departements','DepartementController');
    // FONCTION
    Route::resource('fonctions','FonctionController');
    Route::get('fonctions/{slug}','FonctionController@show')->name('fonctions.show');
});

// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');



Route::resource('employes','EmployeController');
// Route::get('employes/{slug}','EmployeController@show')->name('employes.show');
// Route::get('employes/{slug}','EmployeController@edit')->name('employes.edit');
Route::get('demission-employes/{id}','EmployeController@Demission')->name('demission');

// route training
Route::resource('formations','FormationController');

// gestion des sanction
Route::resource('sanctions','SanctionController');
Route::post('sanctions/{id}','SanctionController@decision')->name('decision.index');






// ABSENCES
Route::resource('absences','AbsenceController');

Route::post('absences/{id}','AbsenceController@justify')->name('justify.index');
// Route::post('absences-arpport/{id}','AbsenceController@rapport')->name('rapport.index');
Route::get('/absences-demission-accepte/{id}', 'AbsenceController@Etat_accepte_demission')->name('accepte_demission');
Route::get('/absences-demission-refuse/{id}','AbsenceController@Etat_refus_demission')->name('refuse_demission');


// CONGES
Route::resource('conges','CongeController');
Route::delete('conges/{slug}', 'CongeController@destroy')->name('conges.destroy');

// Route::get('/liste-conges-en-cours', 'CongeController@listeCongesEnAttente')->name('CongeEnAttente');

Route::get('/conge-valide/{id}', 'CongeController@Accepte')->name('congeValide');
Route::get('/rejetter/{id}','CongeController@Refuse')->name('congeRefuse');
Route::post('/conges/{id}','CongeController@Autorisation')->name('autorisations');



Route::resource('groupes', 'GroupeController');


Route::resource('typeSanctions', 'Type_sanctionController');


Route::resource('dossierEmployes', 'Dossier_employeController');
Route::post('dossier', 'EmployeController@Dossier')->name('dossier.store');


Route::resource('typeFonctions', 'Type_fonctionController');


Route::resource('typeFormations', 'Type_formationController');
Route::get('send', 'HomeController@sendNotification');


Route::resource('villes', 'VilleController');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Sanction.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Sanction extends Model
{
    use HasFactory;
    protected $guarded = [];
    protected $fillable = [
        'employe_id',
        'date_debut',
        'date_fin',
        'Motif',
        'type_sanction_id',
        'decisionSanction',
        'Date_de_comise_la_faute'


    ];

       /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'employe_id' => 'integer',
        'date_debut' => 'string',
        'date_fin' => 'date',
        'Motif' => 'string',
        'decisionSanction' => 'string',
        'type_sanction_id' => 'integer',
        'Date_de_comise_la_faute' => 'string'


    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [

        // 'libelle' => 'required',
        // 'description' => 'required',

    ];
// Un type de sanction appartient a une sanction
    public function type_sanction()
    {
        return $this->belongsTo(Type_sanction::class);
    }
}

app/Http/Controllers/SanctionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Sanction;
use Illuminate\Http\Request;
use App\Models\Employe;
use App\Models\Type_sanction;
use illuminate\Support\Str;

class SanctionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $sanctions = Sanction::get();
        $employes = Employe::all();
        $type_sanctions = Type_sanction::all();
        return view('front.sanctions.index',compact('sanctions','employes','type_sanctions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {      $type_sanctions = Type_sanction::all();
        $employes = Employe::all();
        return view('front.sanctions.create',compact('employes','type_sanctions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $sanctions= new Sanction();
        $sanctions->employe_id = $request->employe_id;
        $sanctions->date_debut = $request->date_debut;
        $sanctions->date_fin = $request->date_fin;
        $sanctions->type_sanction_id = $request->type_sanction_id;
        $sanctions->Date_de_comise_la_faute = $request->Date_de_comise_la_faute;
        $sanctions->motif = $request->motif;
        // $sanctions->nombre_jours_conge = $request->nombre_jours_conge;
        if($request->date_fin<=$request->date_debut){
            return back()->with('La date de debut ne doit pas etre superieur ou egale a la date de fin');
        }
        // dd($sanctions);
        $sanctions->save();

        $slug = Str::of($sanctions->date_debut."60c1e96d9d064c36205c4097".$sanctions->date_fin.$sanctions->created_at)->slug('-');
        $sanctions->slug =  $slug;

        $sanctions->save();

        return redirect()->route('sanctions.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Sanction  $sanction
     * @return \Illuminate\Http\Response
     */
    public function show(Sanction $sanction)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Sanction  $sanction
     * @return \Illuminate\Http\Response
     */
    public function edit(Sanction $sanction)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Sanction  $sanction
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Sanction $sanction)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Sanction  $sanction
     * @return \Illuminate\Http\Response
     */
    public function destroy(Sanction $sanction)
    {
        //
    }

    public function decision(Request $request, $id)
    {
        dd($id);
        $sanction = Sanction::where('id',$id)->find($id);
        // $decisions = new Sanction();
        $sanction->update(request()->all());

        return redirect()->route('sanctions.index');
        // $decisions->decisionSanction = $request->decisionSanction;

    }


}

resources/views/front/sanctions/create.blade.php
<!-- /.card-header -->
<div class="card-body">
    <!-- form start -->
    {{-- @include('flash::message') --}}
   <form method="POST" enctype="multipart/form-data" action="{{route('sanctions.store')}}" id="form1">
       @csrf
       <div class="card-body">
           <div class="row">
               <div class="col-sm-6">
                   <div class="form-group">
                       <label for="exampleInputEmail1">Employé(e)</label>
                       <select name="employe_id" data-placeholder="Select employé" class="form-control form-control-select2 required" data-fouc>
                           <option value="-1" selected="selected">Selectionnez un employé</option>
                                   @foreach ($employes as $employe)
                                   <option value="{{$employe->id}}">{{$employe->nom}} {{$employe->prenom}}</option>
                                   @endforeach
                       </select>
                   </div>
               </div>
               <div class="col-sm-6">
                   <div class="form-group">
                       <label for="exampleInputEmail1">Motif</label>
                       <textarea name="motif" rows="1" class="form-control"></textarea>
                   </div>
               </div>
           </div>
           <div class="row">
               <div class="col-sm-6">
                   <div class="form-group">
                       <label for="">Date debut</label>
                       <div class="input-group date" id="reservationdate" data-target-input="nearest">
                           <input type="text"name="date_debut"id="reservationdate" class="form-control datetimepicker-input" data-target="#reservationdate"/>
                           <div class="input-group-append" data-target="#reservationdate" data-toggle="datetimepicker">
                               <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                           </div>
                       </div>

                   </div>
               </div>
               <div class="col-sm-6">
                   <div class="form-group">
                       <label for="">Date fin:</label>
                       <div class="input-group date" id="reservationdatetwo" data-target-input="nearest">
                           <input type="text"name="date_fin" id="reservationdatetwo" class="form-control datetimepicker-input" data-target="#reservationdatetwo"onkeyup="calculateDifference()"/>
                           <div class="input-group-append" data-target="#reservationdatetwo" data-toggle="datetimepicker">
                               <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                           </div>
                       </div>

                   </div>
               </div>
               <div class="col-sm-6">
                <div class="form-group">
                    <label for="">Date a laquelle la faute a ete comise:</label>
                    <div class="input-group date" id="reservationdatethree" data-target-input="nearest">
                        <input type="text"name="Date_de_comise_la_faute" id="reservationdatethree" class="form-control datetimepicker-input" data-target="#reservationdatethree"onkeyup="calculateDifference()"/>
                        <div class="input-group-append" data-target="#reservationdatethree" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>
                    </div>

                </div>
            </div>
               <div class="col-sm-4">
                   <div class="form-group">
                       <label for="">Type de sanction</label>
                       <select name="type_sanction_id" data-placeholder="" class="form-control form-control-select2 required" data-fouc>
                           <option value="-1" selected="selected">Selectionnez le type de sanction</option>
                           @foreach ($type_sanctions as $type_sanction)
                           <option value="{{$type_sanction->id}}">{{$type_sanction->libelle}}</option>
                           @endforeach
                       </select>
                   </div>
               </div>
           </div>

           <!-- /.card-body -->

           <div class="card-footer">
           <button type="submit" class="btn btn-primary">Enregistrer</button>
           </div>
       </div>
   </form>

</div>
<!-- /.card-body -->

resources/views/front/sanctions/index.blade.php
@extends('layouts.main')
@section('content')


  <!-- Navbar -->
    @include('layouts.header')
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->

  @include('layouts.sidebars')

<div class="wrapper">



  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">


    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">


        <div class="row">

          <div class="col-12 col-sm-12">
            <div class="card card-info card-tabs">
              <div class="p-0 pt-1 card-header">
                <ul class="nav nav-tabs" id="custom-tabs-two-tab" role="tablist">
                  <li class="px-3 pt-2"><h3 class="card-title">Gestion des sanctions</h3></li>
                  @include('flash::message')
                  <li class="nav-item">
                    <a class="nav-link active" id="custom-tabs-two-home-tab" data-toggle="pill" href="#custom-tabs-two-home" role="tab" aria-controls="custom-tabs-two-home" aria-selected="true">Liste des sanctions</a>
                  </li>
                  <li class="nav-item">
                    {{-- <a class="nav-link" id="custom-tabs-two-profile-tab" data-toggle="pill" href="#custom-tabs-two-profile" role="tab" aria-controls="custom-tabs-two-profile" aria-selected="false">Liste des absents</a> --}}
                  </li>
                  <li class="nav-item">
                    {{-- <a class="nav-link" id="custom-tabs-two-messages-tab" data-toggle="pill" href="#custom-tabs-two-messages" role="tab" aria-controls="custom-tabs-two-messages" aria-selected="false">Demisions</a> --}}
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" id="custom-tabs-two-settings-tab" data-toggle="pill" href="#custom-tabs-two-settings" role="tab" aria-controls="custom-tabs-two-settings" aria-selected="false">Ajouter une sanction</a>
                  </li>
                </ul>
              </div>
              <div class="card-body">
                <div class="tab-content" id="custom-tabs-two-tabContent">
                  <div class="tab-pane fade show active" id="custom-tabs-two-home" role="tabpanel" aria-labelledby="custom-tabs-two-home-tab">
                     {{-- Presents --}}
                     <div class="card card-info">
                        <div class="card-header">
                        <h3 class="card-title">Les sanctions </h3>
                        {{-- <span class="breadcrumb float-sm-right"><a href="{{route('absences.create')}}">Marquer une présence</a></span> --}}
                        </div>
                            <!-- /.card-header -->
                            @include("front.sanctions.liste_sanctions")
                            <!-- /.card-body -->
                    </div>
                  </div>
                  <div class="tab-pane fade" id="custom-tabs-two-profile" role="tabpanel" aria-labelledby="custom-tabs-two-profile-tab">
                     {{-- Absence --}}
                     <div class="card card-info">
                        <div class="card-header">
                        <h3 class="card-title">Liste des absents</h3>
                        {{-- <span class="breadcrumb float-sm-right"><a href="{{route('absences.create')}}">Affecter une absence</a></span> --}}
                        </div>
                            <!-- /.card-header -->
                            {{-- @include("front.pointages.absences.absents") --}}
                            <!-- /.card-body -->
                    </div>
                  </div>
                  <div class="tab-pane fade" id="custom-tabs-two-messages" role="tabpanel" aria-labelledby="custom-tabs-two-messages-tab">
                     {{-- Demission --}}
                     <div class="card card-info">
                        <div class="card-header">
                        {{-- <h3 class="card-title">Demissions</h3> --}}
                        {{-- <span class="breadcrumb float-sm-right"><a href="{{route('absences.create')}}">Demande de demission</a></span> --}}
                        </div>
                            <!-- /.card-header -->
                            {{-- @include("front.pointages.absences.demissions") --}}
                            <!-- /.card-body -->
                    </div>
                  </div>
                  <div class="tab-pane fade" id="custom-tabs-two-settings" role="tabpanel" aria-labelledby="custom-tabs-two-settings-tab">
                    <div class="card card-info">
                        <div class="card-header">
                        <h3 class="card-title">Créer une sanction</h3>
                        </div>
                    </div>
                    @include("front.sanctions.create")

                    {{-- <select name="employe_id" data-placeholder="Select employé" class="form-control form-control-select2 required" data-fouc>
                        <option selected="selected">Selectionnez un employé</option>
                                @foreach ($employes as $employe)
                                <option value="{{$employe->id}}">{{$employe->nom}} {{$employe->prenom}}</option>
                                @endforeach
                    </select> --}}
                  </div>
                </div>
              </div>
              <!-- /.card -->
            </div>
          </div>
        </div>



        <!-- /.card -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
@include('layouts.footer')

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->


@endsection

resources/views/front/sanctions/liste_sanctions.blade.php
 <!-- /.card-header -->
 <div class="card-body">
    <table id="example1" class="table table-bordered table-striped">
      <thead>
      <tr>
          <th>Nom et prenoms</th>
          <th>Type de sanction</th>
          <th>Motif</th>
          <th>Date début</th>
          <th>Date fin</th>
          <th class="text-center">Status</th>
          <th>decision</th>
          <th class="text-center">Etat</th>
          <th class="text-center">Action</th>

      </tr>
      </thead>
      <tbody>
        @foreach ($sanctions as $sanction )
            <tr>
                    {{-- <td class="text-center"><img class="rounded img-fluid avatar-40"src="../assets/images/user/01.jpg" alt="profile"></td> --}}
                <td>
                    @php
                        $employes = App\Models\Employe::where('id',$sanction->employe_id)->find($sanction->employe_id);
                        if($employes===null){
                            echo 'Le nom a été supprimé';
                        }else{
                            echo "$employes->nom $employes->prenom";
                        }
                    @endphp

                <td>{{$sanction->type_sanction->libelle}}</td>
                <td>{{$sanction->Motif}}</td>
                <td>{{$sanction->date_debut}}</td>
                <td>{{date('d/m/Y',strtotime($sanction->date_fin))}}</td>
                <td>
                    @if($sanction->is_motif_refus ==0)
                        <div class="d-flex align-items-center list-user-action">
                        <a class="badge badge-warning" data-toggle="tooltip" data-placement="top" title=""
                            data-original-title="En attente" href="#">
                            En attente
                            {{-- <i class="mr-0 ri-user-add-line"></i> --}}
                        </a>
                        @elseif($sanction->is_motif_refus ==1)

                        <a class="badge badge-success" data-toggle="tooltip" data-placement="top" title=""
                            data-original-title="Accepté" href="#">
                            Accepté
                            {{-- <i class="mr-0 ri-pencil-line"></i> --}}
                        </a>
                        @else
                        {{-- <a class="btn btn-sm bg-primary" data-toggle="tooltip" data-placement="top" title=""
                            data-original-title="Delete" href="#">
                            <i class="mr-0 ri-delete-bin-line"></i>
                            </a> --}}
                            <a class="badge badge-danger" data-toggle="tooltip" data-placement="top" title=""
                            data-original-title="Refusé">
                                Refusé
                                {{-- <i class="mr-0 ri-delete-bin-line"></i> --}}

                            </a>
                        </div>
                    @endif
                </td>
                <td>

                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-lg2{{$sanction->id}}">
                            <span style="">decision de sanction</span>
                        </button>
                      {{-- </div> --}}



                     {{-- MODAL1 Absence non justifié --}}
                     <div class="modal fade" id="modal-lg2{{$sanction->id}}">
                        <div class="modal-dialog modal-lg">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h4 class="modal-title">
                                {{-- @php
                                    $employes = App\Models\Employe::where('id',$sanction->employe_id)->find($sanction->employe_id);
                                    if($employes===null){
                                        echo 'Le nom a été supprimé';
                                    }else{
                                        echo "$employes->nom $employes->prenom "."veuillez vous justifier";
                                    }
                                @endphp --}}
                              </h4>
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>
                            <div class="modal-body">
                              <p>
                                <form method="POST" enctype="multipart/form-data" class="wizard-form" action="{{route('justify.index',$sanction->id)}}">
                                    @csrf
                                    {{-- @method('put') --}}
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <div class="form-group">
                                                <label for="">Etablissez une decision de sanction</label>
                                                <textarea required name="decisionSanction" class="form-control" id="summernote" placeholder=""></textarea>
                                            </div>
                                        </div>

                                        {{-- <div class="col-sm-2">
                                            <div class="form-group">
                                                <label for="exampleInputEmail1">Selectionner</label>
                                                <input type="file" name="rapport_explication" class="form-control" id="mobno" placeholder="Remplissez cette fiche de demande d'explication pour justifier votre absence du {{$absence->date_absence}} ">
                                            </div>
                                        </div> --}}
                                    </div>

                                    <div class="modal-footer justify-content-between">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
                                        <button type="submit" class="btn btn-primary">Etablir</button>
                                      </div>
                                </form>
                              </p>
                            </div>

                          </div>
                          <!-- /.modal-content -->
                        </div>
                        <!-- /.modal-dialog -->
                      </div>
                      <!-- /.modal -->
                </td>
                <td>

                </td>
                <td>
                    <div class="d-flex align-items-center list-user-action">
                        <form class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="top" title=""
                        data-original-title="Delete" method="POST" action="{{route('sanctions.destroy',$sanction->id)}}">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class=""><i class="far fa-trash-alt"></i></button>
                        </form>
                    </div>

                </td>
            </tr>
        @endforeach


      </tfoot>
    </table>
  </div>
  <!-- /.card-body -->