routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::group(['middleware'=>'auth'], function(){

    // TYPE DE FORMATION
    Route::resource('typeFormations','TypeFormationController');

    // TYPE FONCTION
    Route::resource('typeFonctions','TypeFonctionController');


    // DEPARTEMENT
    Route::resource('departements','DepartementController');
    // FONCTION
    Route::resource('fonctions','FonctionController');
    Route::get('fonctions/{slug}','FonctionController@show')->name('fonctions.show');
});

// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');



Route::resource('employes','EmployeController');
// Route::get('employes/{slug}','EmployeController@show')->name('employes.show');
// Route::get('employes/{slug}','EmployeController@edit')->name('employes.edit');
Route::get('demission-employes/{id}','EmployeController@Demission')->name('demission');

// route training
Route::resource('formations','FormationController');

// gestion des sanction
Route::resource('sanctions','SanctionController');
Route::post('sanctions/{id}','SanctionController@decision')->name('decision.index');






// ABSENCES
Route::resource('absences','AbsenceController');

Route::post('absences/{id}','AbsenceController@justify')->name('justify.index');
// Route::post('absences-arpport/{id}','AbsenceController@rapport')->name('rapport.index');
Route::get('/absences-demission-accepte/{id}', 'AbsenceController@Etat_accepte_demission')->name('accepte_demission');
Route::get('/absences-demission-refuse/{id}','AbsenceController@Etat_refus_demission')->name('refuse_demission');


// CONGES
Route::resource('conges','CongeController');
Route::delete('conges/{slug}', 'CongeController@destroy')->name('conges.destroy');

// Route::get('/liste-conges-en-cours', 'CongeController@listeCongesEnAttente')->name('CongeEnAttente');

Route::get('/conge-valide/{id}', 'CongeController@Accepte')->name('congeValide');
Route::get('/rejetter/{id}','CongeController@Refuse')->name('congeRefuse');
Route::post('/conges/{id}','CongeController@Autorisation')->name('autorisations');



Route::resource('groupes', 'GroupeController');


Route::resource('typeSanctions', 'Type_sanctionController');


Route::resource('dossierEmployes', 'Dossier_employeController');
Route::post('dossier', 'EmployeController@Dossier')->name('dossier.store');


Route::resource('typeFonctions', 'Type_fonctionController');


Route::resource('typeFormations', 'Type_formationController');
Route::get('send', 'HomeController@sendNotification');


Route::resource('villes', 'VilleController');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Type_fonction.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class Type_fonction
 * @package App\Models
 * @version August 5, 2021, 4:24 pm UTC
 *
 * @property string $libelle
 */
class Type_fonction extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'type_fonctions';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'libelle'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'libelle' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'libelle' => ' required'
    ];

    // Un employe a plusieurs type fonction
    public function employe(){
        return $this->hasMany(Employe::class);
    }


}

app/Http/Controllers/Type_fonctionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateType_fonctionRequest;
use App\Http\Requests\UpdateType_fonctionRequest;
use App\Repositories\Type_fonctionRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class Type_fonctionController extends AppBaseController
{
    /** @var  Type_fonctionRepository */
    private $typeFonctionRepository;

    public function __construct(Type_fonctionRepository $typeFonctionRepo)
    {
        $this->typeFonctionRepository = $typeFonctionRepo;
    }

    /**
     * Display a listing of the Type_fonction.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $typeFonctions = $this->typeFonctionRepository->all();

        return view('type_fonctions.index')
            ->with('typeFonctions', $typeFonctions);
    }

    /**
     * Show the form for creating a new Type_fonction.
     *
     * @return Response
     */
    public function create()
    {
        return view('type_fonctions.create');
    }

    /**
     * Store a newly created Type_fonction in storage.
     *
     * @param CreateType_fonctionRequest $request
     *
     * @return Response
     */
    public function store(CreateType_fonctionRequest $request)
    {
        $input = $request->all();

        $typeFonction = $this->typeFonctionRepository->create($input);

        Flash::success('Type Fonction saved successfully.');

        return redirect(route('typeFonctions.index'));
    }

    /**
     * Display the specified Type_fonction.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $typeFonction = $this->typeFonctionRepository->find($id);

        if (empty($typeFonction)) {
            Flash::error('Type Fonction not found');

            return redirect(route('typeFonctions.index'));
        }

        return view('type_fonctions.show')->with('typeFonction', $typeFonction);
    }

    /**
     * Show the form for editing the specified Type_fonction.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $typeFonction = $this->typeFonctionRepository->find($id);

        if (empty($typeFonction)) {
            Flash::error('Type Fonction not found');

            return redirect(route('typeFonctions.index'));
        }

        return view('type_fonctions.edit')->with('typeFonction', $typeFonction);
    }

    /**
     * Update the specified Type_fonction in storage.
     *
     * @param int $id
     * @param UpdateType_fonctionRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateType_fonctionRequest $request)
    {
        $typeFonction = $this->typeFonctionRepository->find($id);

        if (empty($typeFonction)) {
            Flash::error('Type Fonction not found');

            return redirect(route('typeFonctions.index'));
        }

        $typeFonction = $this->typeFonctionRepository->update($request->all(), $id);

        Flash::success('Type Fonction updated successfully.');

        return redirect(route('typeFonctions.index'));
    }

    /**
     * Remove the specified Type_fonction from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $typeFonction = $this->typeFonctionRepository->find($id);

        if (empty($typeFonction)) {
            Flash::error('Type Fonction not found');

            return redirect(route('typeFonctions.index'));
        }

        $this->typeFonctionRepository->delete($id);

        Flash::success('Type Fonction deleted successfully.');

        return redirect(route('typeFonctions.index'));
    }
}

resources/views/type_fonctions/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Create Type Fonction</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'typeFonctions.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('type_fonctions.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('typeFonctions.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/type_fonctions/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Edit Type Fonction</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($typeFonction, ['route' => ['typeFonctions.update', $typeFonction->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('type_fonctions.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('typeFonctions.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/type_fonctions/fields.blade.php
<!-- Libelle Field -->
<div class="form-group col-sm-6">
    {!! Form::label('libelle', 'Libelle:') !!}
    {!! Form::text('libelle', null, ['class' => 'form-control']) !!}
</div>

resources/views/type_fonctions/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Type Fonctions</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-primary float-right"
                       href="{{ route('typeFonctions.create') }}">
                        Add New
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-body p-0">
                @include('type_fonctions.table')

                <div class="card-footer clearfix">
                    <div class="float-right">
                        
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/type_fonctions/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Type Fonction Details</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('typeFonctions.index') }}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    @include('type_fonctions.show_fields')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/type_fonctions/show_fields.blade.php
<!-- Libelle Field -->
<div class="col-sm-12">
    {!! Form::label('libelle', 'Libelle:') !!}
    <p>{{ $typeFonction->libelle }}</p>
</div>

<!-- Created At Field -->
<div class="col-sm-12">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $typeFonction->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="col-sm-12">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $typeFonction->updated_at }}</p>
</div>

resources/views/type_fonctions/table.blade.php
<div class="table-responsive">
    <table class="table" id="typeFonctions-table">
        <thead>
        <tr>
            <th>Libelle</th>
            <th colspan="3">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($typeFonctions as $typeFonction)
            <tr>
                <td>{{ $typeFonction->libelle }}</td>
                <td width="120">
                    {!! Form::open(['route' => ['typeFonctions.destroy', $typeFonction->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('typeFonctions.show', [$typeFonction->id]) }}"
                           class='btn btn-default btn-xs'>
                            <i class="far fa-eye"></i>
                        </a>
                        <a href="{{ route('typeFonctions.edit', [$typeFonction->id]) }}"
                           class='btn btn-default btn-xs'>
                            <i class="far fa-edit"></i>
                        </a>
                        {!! Form::button('<i class="far fa-trash-alt"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>