routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::group(['middleware'=>'auth'], function(){

    // TYPE DE FORMATION
    Route::resource('typeFormations','TypeFormationController');

    // TYPE FONCTION
    Route::resource('typeFonctions','TypeFonctionController');


    // DEPARTEMENT
    Route::resource('departements','DepartementController');
    // FONCTION
    Route::resource('fonctions','FonctionController');
    Route::get('fonctions/{slug}','FonctionController@show')->name('fonctions.show');
});

// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');



Route::resource('employes','EmployeController');
// Route::get('employes/{slug}','EmployeController@show')->name('employes.show');
// Route::get('employes/{slug}','EmployeController@edit')->name('employes.edit');
Route::get('demission-employes/{id}','EmployeController@Demission')->name('demission');

// route training
Route::resource('formations','FormationController');

// gestion des sanction
Route::resource('sanctions','SanctionController');
Route::post('sanctions/{id}','SanctionController@decision')->name('decision.index');






// ABSENCES
Route::resource('absences','AbsenceController');

Route::post('absences/{id}','AbsenceController@justify')->name('justify.index');
// Route::post('absences-arpport/{id}','AbsenceController@rapport')->name('rapport.index');
Route::get('/absences-demission-accepte/{id}', 'AbsenceController@Etat_accepte_demission')->name('accepte_demission');
Route::get('/absences-demission-refuse/{id}','AbsenceController@Etat_refus_demission')->name('refuse_demission');


// CONGES
Route::resource('conges','CongeController');
Route::delete('conges/{slug}', 'CongeController@destroy')->name('conges.destroy');

// Route::get('/liste-conges-en-cours', 'CongeController@listeCongesEnAttente')->name('CongeEnAttente');

Route::get('/conge-valide/{id}', 'CongeController@Accepte')->name('congeValide');
Route::get('/rejetter/{id}','CongeController@Refuse')->name('congeRefuse');
Route::post('/conges/{id}','CongeController@Autorisation')->name('autorisations');



Route::resource('groupes', 'GroupeController');


Route::resource('typeSanctions', 'Type_sanctionController');


Route::resource('dossierEmployes', 'Dossier_employeController');
Route::post('dossier', 'EmployeController@Dossier')->name('dossier.store');


Route::resource('typeFonctions', 'Type_fonctionController');


Route::resource('typeFormations', 'Type_formationController');
Route::get('send', 'HomeController@sendNotification');


Route::resource('villes', 'VilleController');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/admin/account/index.blade.php
@extends('layouts.main')
@section('content')


  <!-- Navbar -->
    @include('layouts.header')
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->

<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="dist/img/AdminLTELogo.png" alt="" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">Manager Rh</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="pb-3 mt-3 mb-3 user-panel d-flex">
        <div class="image">
          <img src="dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">Alexander Pierce</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <li class="nav-header">Recrutement</li>
          <li class="nav-item">
            <a href="{{route('employes.index')}}" class="nav-link">
              <i class="nav-icon far fa-calendar-alt"></i>
              <p>
                Employés
             
              </p>
            </a>
          </li>

          <li class="nav-header">Pointages</li>
    
          <li class="nav-item">
            <a href="{{route('conges.index')}}" class="nav-link">
              <i class="nav-icon fas fa-file"></i>
              <p>Congés</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{route('absences.index')}}" class="nav-link">
              <i class="nav-icon fas fa-file"></i>
              <p>Absence</p>
            </a>
          </li>
          <li class="nav-header">Formation</li>
          <li class="nav-item">
            <a href="{{route('formations.index')}}" class="nav-link">
              <i class="fas fa-circle nav-icon"></i>
              <p>Formations</p>
            </a>
          </li>

          {{-- <li class="nav-header">Compte</li> --}}
          
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon far fa-plus-square"></i>
              <p>
                Compte
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
                
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="{{route('fonctions.index')}}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Fonction</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="pages/examples/register.html" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Type fonction</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="{{route('typeFormations.index')}}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Type formation</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="{{route('departements.index')}}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Departement</p>
                    </a>
                  </li>
                </ul>
                <li class="nav-header"><a href="">Compte</a></li>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
 <!-- Content Wrapper. Contains page content -->
 <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="mb-2 row">
          <div class="col-sm-6">
            <h1 class="m-0">Dashboard</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard v1</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-info">
              <div class="inner">
                <h3>150</h3>

                <p>Employé(s)</p>
              </div>
              <div class="icon">
                <i class="ion ion-bag"></i>
              </div>
              <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-success">
              <div class="inner">
                <h3>Formation<sup style="font-size: 20px">%</sup></h3>

                <p>Bounce Rate</p>
              </div>
              <div class="icon">
                <i class="ion ion-stats-bars"></i>
              </div>
              <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-warning">
              <div class="inner">
                <h3>44</h3>

                <p>User Registrations</p>
              </div>
              <div class="icon">
                <i class="ion ion-person-add"></i>
              </div>
              <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-danger">
              <div class="inner">
                <h3>65</h3>

                <p>Unique Visitors</p>
              </div>
              <div class="icon">
                <i class="ion ion-pie-graph"></i>
              </div>
              <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
        </div>
        <!-- /.row -->

        <div class="row">

          <!-- right col (We are only adding the ID to make the widgets sortable)-->
          <section class="col-lg-5 connectedSortable">

            <!-- Map card -->
            <div class="card bg-gradient-primary">
              <div class="border-0 card-header">
                <h3 class="card-title">
                  <i class="mr-1 fas fa-map-marker-alt"></i>
                  Visitors
                </h3>
                <!-- card tools -->
                <div class="card-tools">
                  <button type="button" class="btn btn-primary btn-sm daterange" title="Date range">
                    <i class="far fa-calendar-alt"></i>
                  </button>
                  <button type="button" class="btn btn-primary btn-sm" data-card-widget="collapse" title="Collapse">
                    <i class="fas fa-minus"></i>
                  </button>
                </div>
                <!-- /.card-tools -->
              </div>
              <div class="card-body">
                <div id="world-map" style="height: 250px; width: 100%;"></div>
              </div>
              <!-- /.card-body-->
              <div class="bg-transparent card-footer">
                <div class="row">
                  <div class="text-center col-4">
                    <div id="sparkline-1"></div>
                    <div class="text-white">Visitors</div>
                  </div>
                  <!-- ./col -->
                  <div class="text-center col-4">
                    <div id="sparkline-2"></div>
                    <div class="text-white">Online</div>
                  </div>
                  <!-- ./col -->
                  <div class="text-center col-4">
                    <div id="sparkline-3"></div>
                    <div class="text-white">Sales</div>
                  </div>
                  <!-- ./col -->
                </div>
                <!-- /.row -->
              </div>
            </div>
            <!-- /.card -->


            <!-- Calendar -->
            <div class="card bg-gradient-success">
              <div class="border-0 card-header">

                <h3 class="card-title">
                  <i class="far fa-calendar-alt"></i>
                  Calendar
                </h3>
                <!-- tools card -->
                <div class="card-tools">
                  <!-- button with a dropdown -->
                  <div class="btn-group">
                    <button type="button" class="btn btn-success btn-sm dropdown-toggle" data-toggle="dropdown" data-offset="-52">
                      <i class="fas fa-bars"></i>
                    </button>
                    <div class="dropdown-menu" role="menu">
                      <a href="#" class="dropdown-item">Add new event</a>
                      <a href="#" class="dropdown-item">Clear events</a>
                      <div class="dropdown-divider"></div>
                      <a href="#" class="dropdown-item">View calendar</a>
                    </div>
                  </div>
                  <button type="button" class="btn btn-success btn-sm" data-card-widget="collapse">
                    <i class="fas fa-minus"></i>
                  </button>
                  <button type="button" class="btn btn-success btn-sm" data-card-widget="remove">
                    <i class="fas fa-times"></i>
                  </button>
                </div>
                <!-- /. tools -->
              </div>
              <!-- /.card-header -->
              <div class="pt-0 card-body">
                <!--The calendar -->
                <div id="calendar" style="width: 100%"></div>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </section>
          <!-- right col -->
        </div>
        <!-- /.row (main row) -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  {{-- footer --}}
  @include('layouts.footer')
  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

@endsection